---
- name: Add docker-ce repo
  get_url:
    url: https://download.docker.com/linux/centos/docker-ce.repo
    dest: /etc/yum.repos.d/docker-ce.repo
    mode: '0644'
    owner: root
    group: root

- name: Install docker-ce
  command: dnf install {{ item }} --nobest -y
  with_items:
    - "{{ docker_packages }}"
  args:
    warn: false
  notify:
    - enable docker
    - start docker
  changed_when: false
