- name: Add docker-ce gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add docker-ce repository
  apt_repository:
    repo: deb [arch={{ ansible_architecture }}] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    state: present

- name: Install docker-ce
  apt:
    name: "{{ docker_packages }}"
  notify:
    - enable docker
    - start docker
