---
language: python
services: docker
os: linux
dist: bionic
env:
  - MOLECULE_DISTRO: centos8
  - MOLECULE_DISTRO: centos7
  - MOLECULE_DISTRO: debian10
  - MOLECULE_DISTRO: ubuntu20.04
  - MOLECULE_DISTRO: ubuntu18.04
  - MOLECULE_DISTRO: ubuntu16.04
    #  - MOLECULE_DISTRO: fedora33
  - MOLECULE_DISTRO: fedora32
  - MOLECULE_DISTRO: fedora31
  - MOLECULE_DISTRO: fedora30

install:
  - pip install molecule molecule-docker yamllint ansible-lint docker
before_script:
  - cd .. && mv ansible-docker-installation docker_installation && cd docker_installation
script:
  - molecule test
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
